package constant;

import lombok.Getter;

@Getter
public enum ResponseStatus {
    LOGIN_SUCCESS_STATUS(1),
    LOGIN_FAIL_STATUS(0),
    CREATED_USER_SUCCESS(201),
    CREATED_USER_FAIl(400),
    CREATED_COURSE_FAIl(401),
    UPDATE_COURSE_FAIl(403),
    DELETE_COURSE_FAIL(404),
    GET_COURSEDETAIL_FAIL(405),
    CREATE_COUSRECONTENT_FAIL(406),
    CREATE_COURSETEST_FAIL(407),
    GET_USERS_FAIL(408),
    DELETE_USER_FAIL(409),
    GET_COURSETESTRESULT_FAIL(410),
    GET_CLASSDETAIL_FAIL(411),
    GET_CLASSOVERVIEW_FAIL(412),
    CREATE_CLASSROOM_FAIL(413),
    JOIN_CLASSROOM_FAIL(414),
    UNENROLL_FAIL(415),
    LEAVE_CLASSROOM_FAIL(416),
    GET_RESULTASSIGNMENT_FAIL(417),
    SUBMIT_ASSIGNMENT_FAIL(418),
    CHANGE_ROLE_FAIL(419),
    CREATE_ASSIGNMENT_FAIL(420),
    GET_SUBMISSION_FAIL(421),
    GET_ASSIGNMENT_FAIL(422),
    GET_COURSECONTENT_FAIL(422),
    GET_COURSETEST_FAIL(423),
    GET_ENROLLCLASSROOM_FAIL(424),
    ENROLL_FAIL(425),
    INVALID_INPUT(425),

    CREATED_COURSE_SUCCESS(202),
    UPDATE_COURSE_SUCCESS(203),
    DELETE_COURSE_SUCCESS(204),
    GET_COURSEDETAIL_SUCCESS(205),
    CREATE_COURSECONTENT_SUCCESS(206),
    CREATE_COURSETEST_SUCCESS(207),
    GET_USER_SUCCESS(208),
    DELETE_USER_SUCCESS(209),
    GET_COURSETESTRESULT_SUCCESS(210),
    GET_CLASSDETAIL_SUCCESS(211),
    GET_CLASSOVERVIEW_SUCCESS(212),
    CREATE_CLASSROOM_SUCCESS(213),
    JOIN_CLASSROOM_SUCCESS(214),
    UNENROLL_SUCCESS(215),
    LEAVE_CLASSROOM_SUCCESS(216),
    GET_RESULTASSIGNMENT_SUCESS(217),
    SUBMIT_ASSIGNMENT_SUCCESS(218),
    CHANGE_ROLE_SUCESS(219),
    CREATE_ASSIGNMENT_SUCCESS(220),
    GET_SUBMISSION_SUCCESS(221),

    FAIL(499),
    SUCCESS(200);

    int status;
    ResponseStatus(int status){
        this.status = status;
    }
}
