package exception;

import constant.Message;
import constant.ResponseStatus;
import lombok.Getter;
import org.springframework.http.HttpStatus;

@Getter
public enum ErrorCode {
    CREATED_USER_FAIL(ResponseStatus.CREATED_USER_FAIl, Message.CREATED_USER_FAIL, HttpStatus.BAD_REQUEST),
    CREATED_COURSE_FAIL(ResponseStatus.CREATED_COURSE_FAIl, Message.CREATED_COURSE_FAIL, HttpStatus.BAD_REQUEST),
    UPDATE_COURSE_FAIL(ResponseStatus.UPDATE_COURSE_FAIl, Message.UPDATE_COURSE_FAIL, HttpStatus.BAD_REQUEST),
    DELETE_COURSE_FAIL(ResponseStatus.DELETE_COURSE_FAIL, Message.DELETE_COURSE_FAIL, HttpStatus.BAD_REQUEST),
    GET_COURSEDETAIL_FAIL(ResponseStatus.GET_COURSEDETAIL_FAIL, Message.GET_COURSEDETAIL_FAIL, HttpStatus.NOT_FOUND),
    CREATE_COURSECONTENT_FAIL(ResponseStatus.CREATE_COUSRECONTENT_FAIL, Message.CREATE_COURSECONTENT_FAIL, HttpStatus.BAD_REQUEST),
    CREATE_COURSETEST_FAIL(ResponseStatus.CREATE_COURSETEST_FAIL, Message.CREATE_COURSETEST_FAIL, HttpStatus.BAD_REQUEST),
    GET_USERS_FAIL(ResponseStatus.GET_USERS_FAIL, Message.GET_USERS_FAIL, HttpStatus.NOT_FOUND),
    DELETE_USER_FAIL(ResponseStatus.DELETE_USER_FAIL, Message.DELETE_USER_FAIL, HttpStatus.BAD_REQUEST),
    GET_COURSETESTRESULT_FAIL(ResponseStatus.GET_COURSETESTRESULT_FAIL, Message.GET_COURSETESTRESULT_FAIL, HttpStatus.NOT_FOUND),
    GET_CLASSDETAIL_FAIL(ResponseStatus.GET_CLASSDETAIL_FAIL, Message.GET_CLASSDETAIL_FAIL, HttpStatus.NOT_FOUND),
    GET_CLASSOVERVIEW_FAIL(ResponseStatus.GET_CLASSOVERVIEW_FAIL, Message.GET_CLASSOVERVIEW_FAIL, HttpStatus.NOT_FOUND),
    CREATE_CLASSROOM_FAIL(ResponseStatus.CREATE_CLASSROOM_FAIL, Message.CREATE_CLASSROOM_FAIL, HttpStatus.BAD_REQUEST),
    JOIN_CLASSROOM_FAIL(ResponseStatus.JOIN_CLASSROOM_FAIL, Message.JOIN_CLASSROOM_FAIL, HttpStatus.BAD_REQUEST),
    UNENROLL_FAIL(ResponseStatus.UNENROLL_FAIL, Message.UNENROLL_FAIL, HttpStatus.BAD_REQUEST),
    ENROLL_FAIL(ResponseStatus.ENROLL_FAIL, Message.ENROLL_FAIL, HttpStatus.BAD_REQUEST),
    LEAVE_CLASSROOM_FAIL(ResponseStatus.LEAVE_CLASSROOM_FAIL, Message.LEAVE_CLASSROOM_FAIL, HttpStatus.BAD_REQUEST),
    GET_RESULTASSIGNMENT_FAIL(ResponseStatus.GET_RESULTASSIGNMENT_FAIL, Message.GET_RESULTASSIGNMENT_FAIL, HttpStatus.NOT_FOUND),
    SUBMIT_ASSIGNMENT_FAIL(ResponseStatus.SUBMIT_ASSIGNMENT_FAIL, Message.SUBMIT_ASSIGNMENT_FAIL, HttpStatus.BAD_REQUEST),
    CHANGE_ROLE_FAIL(ResponseStatus.CHANGE_ROLE_FAIL, Message.CHANGE_ROLE_FAIL, HttpStatus.BAD_REQUEST),
    CREATE_ASSIGNMENT_FAIL(ResponseStatus.CREATE_ASSIGNMENT_FAIL, Message.CREATE_ASSIGNMENT_FAIL, HttpStatus.BAD_REQUEST),
    GET_COURSES_FAIL(ResponseStatus.FAIL, Message.GET_COURSES_FAIL, HttpStatus.BAD_REQUEST),
    GET_ASSIGNMENT_FAIL(ResponseStatus.GET_ASSIGNMENT_FAIL, Message.GET_ASSIGNMENT_FAIL, HttpStatus.BAD_REQUEST),
    GET_COURSECONTENT_FAIL(ResponseStatus.GET_COURSECONTENT_FAIL, Message.GET_COURSECONTENT_FAIL, HttpStatus.BAD_REQUEST),
    GET_COURSETEST_FAIL(ResponseStatus.GET_COURSETEST_FAIL, Message.GET_COURSETEST_FAIL, HttpStatus.BAD_REQUEST),
    GET_ENROLLCLASS_FAIL(ResponseStatus.GET_ENROLLCLASSROOM_FAIL, Message.GET_ENROLLCLASROOM_FAIL, HttpStatus.BAD_REQUEST),
    INVALID_INPUT(ResponseStatus.INVALID_INPUT, Message.INVALID_INPUT, HttpStatus.BAD_REQUEST),
    GET_SUBMISSION_FAIL(ResponseStatus.GET_SUBMISSION_FAIL, Message.GET_SUBMISSION_FAIL, HttpStatus.NOT_FOUND);


    private final int code;
    private final String message;
    private final HttpStatus statusCode;

    ErrorCode(ResponseStatus responseStatus, Message msg, HttpStatus status) {
        this.code = responseStatus.getStatus();
        this.message = msg.getMessage();
        this.statusCode = status;
    }
}
